### ISSUE TITLE
add autoscaling

### ISSUE THREAD

**Issue by hnykda** [epidemics/covid#35]
Currently, we don't handle autoscaling anyhow intelligently.

The main node pool has scaling from 0-5 replicas, but the services themselves not and replicas are set to 1. 

Using [horizontal pod autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#autoscaling-on-multiple-metrics-and-custom-metrics) would probably help, even the default one:

```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
```
