### ISSUE TITLE
Custom consume site (backend side)

### ISSUE THREAD

**Issue by mathijshenquet** [epidemics/covid#400]
Related to #391 and #398 

The frontend expects:
 - Scenarios: https://github.com/epidemics/covid/blob/v4/common/spec/v4.ts#L62-L66
 - Description: https://github.com/epidemics/covid/blob/v4/common/spec/v4.ts#L72

**Comment by hnykda** [comment]
I didn't think that scenarios are going to be different _per region_ (or did I miss that from Jacob's description?). But OK I guess, especially given it's in the country-specific file. 

>  I propose that we expand the config.yaml spec such that instead of specificying just a country code you can instead specify an object with something like the following type

If we went with this way... I assume that it would be present in the country specific file if and only if there is an "override" via the config. 

I propose the config is like:

```
models_override:
 UK:
    modelDescription: |
     <p>
       My special text
     </p>
    scenarios:
      - group: Low
        name: Small mitigation
        description: This is a small mitigation like washing your ears
      - group: High
        name: Big mitigation
        description: These are huge mitigation like washing your neighbor
  BR: 
    ...
```
and during the runtime, we would check that `groups` are in sync with `groups` from the top level.
